### ISSUE TITLE
1.1.0: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [numpy/numpydoc#346]
Looks like sphinx is failing on rendering module documentation.
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
making output directory... done
[autosummary] generating autosummary for: example.rst, format.rst, index.rst, install.rst, release_notes.rst, validation.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/devdocs/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [100%] validation
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... numpydoc.1 { install release_notes format example validation } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 1034, in replace_self
    assert not self[att], \
AssertionError: Losing "ids" attribute: ['id2']
The full traceback has been saved in /tmp/sphinx-err-pftdjvpg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@ss-desktop SPECS]$ cat /tmp/sphinx-err-pftdjvpg.log
# Sphinx version: 4.3.2
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   done
#   writing...
#   numpydoc.1 {
#   install
#   release_notes
#   format
#   example
#   validation
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.doctest (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/todo.py
#   numpydoc (1.1.0) from /home/tkloczko/rpmbuild/BUILD/numpydoc-1.1.0/numpydoc/__init__.py
#   sphinx.ext.ifconfig (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.viewcode (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.imgmath (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/imgmath.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 175, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 99, in write
    self.env.resolve_references(largetree, docname, self)
  File "/usr/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 569, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/usr/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 581, in apply_post_transforms
    transformer.apply_transforms()
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/post_transforms/__init__.py", line 43, in apply
    self.run(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/post_transforms/__init__.py", line 121, in run
    node.replace_self(newnodes)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 1034, in replace_self
    assert not self[att], \
AssertionError: Losing "ids" attribute: ['id2']
```

**Comment by rossbar** [comment]
I can reproduce, but only with the setup.py build_sphinx invocation - I don't have any problems when running with sphinx directly, e.g. `make html` or `sphinx-build -b html -d _build/doctrees  -nWT --keep-going . _build/html`.

**Comment by kloczek** [comment]
What you've tested is not the same because you are producing html and I'm interested roff foile (man page). Probably if you will execute `sphinx-build -b man -d _build/doctrees -nWT --keep-going . _build/man` you would be able to reproduce that,
sphinx<>setuptools integration it is only handy wrapper around `sphinx-build` command allowing to use(always) the same command without care where is located conf.py file and documentation root directory.

**Comment by mattip** [comment]
Perhaps numpydoc should detect a call to create man pages and raise a nicer error "man page output not supported at this time" until someone shows a use case for sphinx generated man pages. See a [discussion on the numpy issue tracker](https://github.com/numpy/numpy/issues/20229#issuecomment-977722433) where the **need** for man pages was never clearly articulated.

**Comment by kloczek** [comment]
Here it is my use case.
I have already packaged +760 python modules and more than half of those packages have documentation as man pages.
Just glimpse from my current (small) devel env:
```console
[tkloczko@ss-desktop SPECS]$ man python-<tab><tab>
python-attrs                              python-html5lib                           python-pillow                             python-secretstorage
python-backports.entry-points-selectable  python-httpretty                          python-pkginfo                            python-setuptools
python-build                              python-importlib-metadata                 python-platformdirs                       python-six
python-cachecontrol                       python-jeepney                            python-pluggy                             python-smartypants
python-cffi                               python-keyring                            python-prb                                python-testtools
python-chardet                            python-kiwi                               python-ptyprocess                         python-urllib3
python-charset-normalizer                 python-lxml                               python-py                                 python-virtualenv
python-dateutil                           python-mako                               python-pygments                           python-webencodings
python-dbus                               python-markupsafe                         python-pyparsing                          python-wheel
python-filelock                           python-msgpack                            python-pytest                             python-youtube-dl
python-fonttools                          python-olefile                            python-requests                           python-zipp
python-gidocgen                           python-pep517                             python-requests_toolbelt
```
And some stats showing exactly how many python module packaged as rpm packages and in how many of those packages is used macro used to generate man page(s):
```console
[tkloczko@ss-desktop SPECS]$ ls -1 python-* | wc -l; grep %py3_build_sphinx_man python-* | wc -l
760
396
```
Man page it is still basic format of the documentation used on all Unix platforms :)
```

**Comment by rgommers** [comment]
We do not support man pages. 

> I have already packaged +750 python modules as rpm packages and more than half of those packages have documentation as man pages.

That's not a need, man pages are for command line tools. NumPy does not support them. The discussion to change that is in https://github.com/numpy/numpy/issues/20229. Please do not start duplicate discussions on multiple trackers.

**Comment by kloczek** [comment]
Just checked 1.3.0 and looks like man page can be now generated.
Thank you 😃
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
[autosummary] generating autosummary for: example.rst, format.rst, index.rst, install.rst, release_notes.rst, validation.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/devdocs/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [100%] validation
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... numpydoc.1 { install format validation release_notes example } done
build succeeded.
```
