### ISSUE TITLE
Weird docstring error when running numpydoc?

### ISSUE THREAD

**Issue by adam2392** [numpy/numpydoc#386]
I am running sphinx which runs numpydoc checks, and I get this weird error.

I tried parsing it, but do not understand where this is coming from. Nowhere in my doctoring do I have a yield and return section I think(?)

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/numpydoc/numpydoc.py", line 229, in mangle_signature
    doc = get_doc_object(obj, config={'show_class_members': False})
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/numpydoc/docscrape_sphinx.py", line 442, in get_doc_object
    return SphinxFunctionDoc(obj, doc=doc, config=config)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/numpydoc/docscrape_sphinx.py", line 396, in __init__
    FunctionDoc.__init__(self, obj, doc=doc, config=config)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/numpydoc/docscrape.py", line 572, in __init__
    NumpyDocString.__init__(self, doc, config)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/numpydoc/docscrape.py", line 147, in __init__
    self._parse()
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/numpydoc/docscrape.py", line 388, in _parse
    raise ValueError(msg)
ValueError: Docstring contains both a Returns and Yields section.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 3008, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 258, in run
    items = self.get_items(names)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 385, in get_items
    sig = documenter.format_signature(show_annotation=False)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 1337, in format_signature
    sig = super().format_signature(**kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 1254, in format_signature
    sig = super().format_signature(**kwargs)  # type: ignore
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 517, in format_signature
    result = self.env.events.emit_firstresult('autodoc-process-signature',
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/events.py", line 112, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
  File "/usr/local/Caskroom/miniconda/base/envs/causal/lib/python3.9/site-packages/sphinx/events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function mangle_signature at 0x7fda20b984c0> for event 'autodoc-process-signature' threw an exception (exception: Docstring contains both a Returns and Yields section.)
```

**Comment by adam2392** [comment]
If it helps, commit https://github.com/adam2392/causal-networkx/pull/1/commits/47aa30822a65847c7804e4c63e7015138cbc91a9

from https://github.com/adam2392/causal-networkx/pull/1 is what's causing the error.

**Comment by rkern** [comment]
> Nowhere in my doctoring do I have a yield and return section I think(?)

[Here it is.](https://github.com/adam2392/causal-networkx/blob/f023697cddffdf3522b89eccb652c7423ca3caa6/causal_networkx/algorithms/cliques.py#L16-L22)

**Comment by adam2392** [comment]
Doh... my bad. I searched on the wrong folder :/
