### ISSUE TITLE
numpydoc-1.3.tar.gz on pypi is missing requirements/ needed by setup.py

### ISSUE THREAD

**Issue by mgorny** [numpy/numpydoc#387]
When trying to build using [numpydoc-1.3.tar.gz](https://files.pythonhosted.org/packages/fa/a3/ed85fae396079ea101f18b9d7ae64c98fde36f2115ef39d087341d254ec5/numpydoc-1.3.tar.gz) from pypi:

```
$ python setup.py build
Traceback (most recent call last):
  File "/tmp/numpydoc-1.3/setup.py", line 58, in <module>
    req for req in read('requirements/test.txt').split('\n')
  File "/tmp/numpydoc-1.3/setup.py", line 25, in read
    with open(os.path.join(os.path.dirname(__file__), fname)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/numpydoc-1.3/requirements/test.txt'
```

**Comment by mgorny** [comment]
Thanks!
