### ISSUE TITLE
numpydoc breaks Sphinx' gettext

### ISSUE THREAD

**Issue by f0k** [numpy/numpydoc#90]
As reported in  sphinx-doc/sphinx#915 and sphinx-doc/sphinx#3510, when using numpydoc, the [gettext builder of Sphinx](http://www.sphinx-doc.org/en/stable/intl.html) fails. In those two issues, the conclusion has been that the error lies within numpydoc, not within Sphinx.

Steps to reproduce:
```bash
mkdir /tmp/foo
cd /tmp/foo
cat <<'EOF' >> conf.py
master_doc = 'index'
extensions = ['sphinx.ext.autodoc', 'numpydoc']
EOF
cat <<'EOF' >> index.rst
.. autofunction:: sphinx.main()

   hello world
EOF
sphinx-build -P -T -b gettext -d _build/doctree . _build/locale
```
The output will look as follows:
```
Making output directory...
Running Sphinx v1.2.3
loading pickled environment... not yet created
building [gettext]: targets for 0 template files
building [gettext]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                  
Exception occurred while building, starting debugger:                           
Traceback (most recent call last):
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/builders/gettext.py", line 177, in build
    I18nBuilder.build(self, docnames, summary, method)
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 279, in build
    self.finish()
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/builders/gettext.py", line 206, in finish
    for source, line, _ in positions))
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/builders/gettext.py", line 206, in <genexpr>
    for source, line, _ in positions))
  File "/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/util/osutil.py", line 160, in safe_relpath
    return relpath(path, start)
  File "/usr/lib/python2.7/posixpath.py", line 438, in relpath
    path_list = [x for x in abspath(path).split(sep) if x]
  File "/usr/lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: StringList instance has no attribute 'startswith'
> /usr/lib/python2.7/posixpath.py(61)isabs()
-> return s.startswith('/')
(Pdb) 
```
The issue is the same with sphinx 1.5.3. Poking around in the debugger, the problem is that in https://github.com/sphinx-doc/sphinx/blob/1.5.3/sphinx/builders/gettext.py#L237, `source` is expected to be a string, but is a `docutils.state_machine.StringList` instead:
```
(Pdb) u
> /usr/lib/python2.7/posixpath.py(367)abspath()
-> if not isabs(path):
(Pdb) u
> /usr/lib/python2.7/posixpath.py(438)relpath()
-> path_list = [x for x in abspath(path).split(sep) if x]
(Pdb) u
> /raid/user/jan/.local/lib/python2.7/site-packages/sphinx/util/osutil.py(160)safe_relpath()
-> return relpath(path, start)
(Pdb) u
> /raid/user/jan/.local/lib/python2.7/site-packages/sphinx/builders/gettext.py(206)<genexpr>()
-> for source, line, _ in positions))
(Pdb) p source
StringList([u'main()', u':module: sphinx', u'', u'', u'', u'', u'', u'hello world'], items=[('<autodoc>', 0), ('<autodoc>', 0), ('<autodoc>', 0), (u'/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/__init__.py:docstring of sphinx.main', 0), (u'/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/__init__.py:docstring of sphinx.main', 1), (u'/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/__init__.py:docstring of sphinx.main', 2), (u'/raid/user/jan/.local/lib/python2.7/site-packages/sphinx/__init__.py:docstring of sphinx.main', 3), (u'/tmp/foo/index.rst', 2)])
```

This seems to be some mapping of output lines to source code lines. Any idea where this originates? Is numpydoc doing anything creative that works fine for the html builder, but not the gettext builder? I'm not sure yet whether numpydoc or gettext is at fault, but I'd like to find out.
FWIW, note that the error disappears if removing either the `.. autofunction` or the `hello world` line from `index.rst`, or `numpydoc` from `conf.py`.

**Comment by jnothman** [comment]
I can't reproduce this error with numpydoc 0.7.0, sphinx 1.5 or 1.6.3.  I can see vaguely how it might possibly derive from `wrap_mangling_directive` but it's hard for me to tell.

**Comment by f0k** [comment]
Oh, indeed! I can confirm that the error does not appear with numpydoc 0.7. Closing!
